name: Build Lambda Package

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23'

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap ./cmd/lambda/main.go

      - name: Create Zip
        run:  zip ./deploy/terraform/lambda_test.zip bootstrap

