name: terraform_plan.yaml
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./deploy/terraform

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.12.2'

      - name: Build
        run: |
          cd ../../src
          GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o ../deploy/terraform/bootstrap ./cmd/lambda/main.go

      - name: Create Zip
        run: |
          zip lambda_$GITHUB_SHA.zip bootstrap

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -var "githubSHA=$GITHUB_SHA" \
          -var "email_recipients=${{ secrets.EMAIL_RECIPIENTS }}" \
          -var "email_server_password = ${{ secrets.EMAIL_SERVER_PASSWORD }} \
          -var "service_email=${{ secrets.SERVICE_EMAIL }}" \
          -var "email_server=${{ secrets.EMAIL_SERVER }}"

      - name: Create code block comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ```
            ${{ steps.plan.outputs.stdout }}
            ```
          GITHUB_TOKEN: ${{ github.token }}

