name: terraform_plan.yaml
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./deploy/terraform

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.12.2'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          cd ../../src
          GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap ./cmd/lambda/main.go

      - name: Create Zip
        run: |
          zip lambda_$GITHUB_SHA.zip ../../src/bootstrap

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        env:
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS}}
          EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}
          SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
        run: |
          terraform plan -no-color -var "githubSHA=$GITHUB_SHA"

      - name: Comment on PR (only if not already posted)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh pr comment ${{ github.event.pull_request.number }} \
              --body "### [AUTO-COMMENT] Terraform Plan
            \`\`\`hcl
             ${{ steps.plan.outputs.stdout }}
            \`\`\`
            " 
