name: terraform_plan.yaml
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./deploy/terraform

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.12.2'

      - name: Build
        run: |
          cd ../../src
          GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap ./cmd/lambda/main.go

      - name: Create Zip
        run: |
          zip lambda_$GITHUB_SHA.zip ../../src/bootstrap

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        env:
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS}}
          EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}
          SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
        run: |
          terraform plan -no-color -out tfplan -var "githubSHA=$GITHUB_SHA"

      - name: Post Terraform Plan to PR with curl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Read plan output and truncate to 65k characters
          PLAN_OUTPUT=$(head -c 65000 tfplan)

          # Wrap in code block and escape double quotes
          COMMENT_BODY=$(jq -Rs . <<< "### Terraform Plan Output
  
          \`\`\`hcl
          $PLAN_OUTPUT
          \`\`\`
          ")

          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"body\": $COMMENT_BODY}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" 
