name: Build Lambda Package

on:
  push:
    branches:
      - "main"

defaults:
  run:
    working-directory: ./deploy/terraform

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23'

      - name: Build
        run: |
          cd ../../src
          GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o ../deploy/terraform/bootstrap ./cmd/lambda/main.go

      - name: Create Zip
        run: |
          zip lambda_$GITHUB_SHA.zip bootstrap 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.12.2'

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        env:
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS}}
          EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}
          SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
        run: terraform apply --auto-approve -var "githubSHA=$GITHUB_SHA"



